version: '3'

volumes:
  moloch:
    driver: local
  esdata:
    driver: local

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    volumes: 
      - esdata:/usr/share/elasticsearch/data
  moloch:
    build:
       context: .
    image: piesecurity/docker-moloch
    environment:
#Make this line true on first execution and false every other time
      - INITALIZEDB=true
      - MOLOCH_PASSWORD=PASSWORDCHANGEME
      - WIPEDB=false
      - MOLOCH_VERSION=1.5.3-1_amd64
      - UBUNTU_VERSION=18.04
      - ES_HOST=elasticsearch
      - ES_PORT=9200
      - MOLOCH_INTERFACE=eth0
      - CAPTURE=off
      - VIEWER=on
    depends_on:
      - elasticsearch
    ports:
      - 0.0.0.0:8005:8005
    volumes:
      - ./tcpdump:/data/pcap
      - ./etc:/data/moloch/etc
      - ./logs:/data/moloch/logs
      - ./raw:/data/moloch/raw
      - moloch:/data/configured
